# Generated by Django 3.2.6 on 2021-09-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='created_ad',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
