# Generated by Django 3.2.6 on 2021-09-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210906_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='user_last_request',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
