# Generated by Django 3.2.6 on 2021-09-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_useractivity_user_last_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='user_last_request',
            field=models.TextField(blank=True, null=True),
        ),
    ]
